[project]
name = "iaawb"
version = "0.1.0"
description = "i am afraid arch will break"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.15.0",
    "python-dotenv>=1.1.0",
]
